---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    name: "{{ item.name }}"
    cloud: ospcloud
    delete_fip: yes
    flavor: "{{ item.flavor }}"
    floating_ip_pools: "{{ osp_floating_ip_network }}"
    image: "{{ item.image }}"
    key_name: "{{ item.key_name }}"
    meta: "{{ item.meta }}"
    nics:
      - net-name: "{{ osp_private_network }}"
    security_groups: "{{ item.security_group | list }}"
    state: "{{ item.state }}"
    userdata: "{{ osp_userdata }}"
    wait: yes
  loop: "{{ osp_servers }}"

- name: Obtain current state of instances
  os_server_facts:
    server: "*"
    cloud: ospcloud
    filters:
      vm_state: stopped
  register: stopped_instances

- name: Power on instances if required
  os_server_action:
    server: "{{ item.name }}"
    action: start
    cloud: ospcloud
  loop: "{{ stopped_instances.ansible_facts.openstack_servers }}"
  when: (stopped_instances | length) > 0
