---
# tasks file for base-config
- debug:
    var: ansible_facts
- name: Enable repos
  get_url:
    url: "{{ internal_repo_url }}"
    dest: /etc/yum.repos.d/internal.repo
    mode: 0644
  when: ansible_facts['deployment_name'] is defined or ansible_facts['deployment_name'] == 'QA'
